// Auto-generated by blockchain/scripts/deploy.js — do NOT edit manually.
module.exports = {
  CONTRACT_ADDRESS: "0xDBC6F74e157C05e31Ad2E4e625b254d993E58f1D",
  USDC_ADDRESS: "0x41bF18b28379CFcAef078407E8ca9F48704A80e4",
  DEPLOYED_NETWORK: "sepolia"
};
