// Auto-generated by blockchain/scripts/deploy.js — do NOT edit manually.
// Regenerate: npx hardhat run scripts/deploy.js --network <network>

export const CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
export const DEPLOYED_NETWORK = "localhost";
export const DEPLOYED_AT      = "2026-04-26T09:16:53.173Z";
