// Auto-generated by blockchain/scripts/deploy.js — do NOT edit manually.
// Regenerate: npx hardhat run scripts/deploy.js --network <network>

export const CONTRACT_ADDRESS = "0xDBC6F74e157C05e31Ad2E4e625b254d993E58f1D";
export const USDC_ADDRESS     = "0x41bF18b28379CFcAef078407E8ca9F48704A80e4";
export const DEPLOYED_NETWORK = "sepolia";
export const DEPLOYED_AT      = "2026-06-16T16:31:48.521Z";
