const hre  = require("hardhat");
const fs   = require("fs");
const path = require("path");

async function main() {
  // ── 1. Log which network we are deploying to ──────────────────────────
  const network = hre.network.name;
  console.log(`\n🚀 Deploying TransparentFund to network: ${network}`);

  // ── 2. Get deployer wallet info ────────────────────────────────────────
  const [deployer] = await hre.ethers.getSigners();
  console.log(`📦 Deploying from wallet:  ${deployer.address}`);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log(`💰 Wallet balance:          ${hre.ethers.formatEther(balance)} ETH/MATIC\n`);

  // ── 3. Deploy the contract ─────────────────────────────────────────────
  const TransparentFund = await hre.ethers.getContractFactory("TransparentFund");
  const fund = await TransparentFund.deploy();
  await fund.waitForDeployment();

  const address = await fund.getAddress();
  console.log(`✅ TransparentFund deployed to: ${address}`);

  // ── 4. Save address to frontend utils ─────────────────────────────────
  //    Tries two common folder layouts. Warns instead of crashing if both fail.
  const configContent =
`// Auto-generated by blockchain/scripts/deploy.js — do NOT edit manually.
// Regenerate: npx hardhat run scripts/deploy.js --network <network>

export const CONTRACT_ADDRESS = "${address}";
export const DEPLOYED_NETWORK = "${network}";
export const DEPLOYED_AT      = "${new Date().toISOString()}";
`;

  const candidates = [
    path.join(__dirname, "../../frontend/src/utils/contractAddress.js"),
    path.join(__dirname, "../frontend/src/utils/contractAddress.js"),
  ];

  let saved = false;
  for (const dest of candidates) {
    try {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, configContent);
      console.log(`📁 Contract address saved to: ${dest}`);
      saved = true;
      break;
    } catch (_) {
      // try next candidate silently
    }
  }

  if (!saved) {
    console.warn("\n⚠️  Could not auto-save to frontend. Add this manually to contractAddress.js:");
    console.warn(`   CONTRACT_ADDRESS = "${address}"`);
    console.warn(`   DEPLOYED_NETWORK = "${network}"\n`);
  }

  // ── 5. Save a deployment record inside blockchain/deployments/ ─────────
  //    Keeps a history of every deployment per network
  const deploymentsDir = path.join(__dirname, "../deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });
  const record = {
    network,
    address,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
  };
  const recordPath = path.join(deploymentsDir, `${network}.json`);
  fs.writeFileSync(recordPath, JSON.stringify(record, null, 2));
  console.log(`📋 Deployment record saved to: ${recordPath}`);

  // ── 6. Verify on Polygonscan / Etherscan (skipped for local networks) ──
  if (network !== "localhost" && network !== "hardhat") {
    console.log("\n⏳ Waiting 10s before verification (block indexing delay)…");
    await new Promise(r => setTimeout(r, 10_000));
    try {
      await hre.run("verify:verify", {
        address,
        constructorArguments: [],
      });
      console.log("✅ Contract verified on block explorer");
    } catch (e) {
      // Not fatal — already verified or API key missing
      console.warn("⚠️  Verification skipped:", e.message);
    }
  }

  console.log("\n🎉 Deployment complete!\n");
}

main().catch(error => {
  console.error("❌ Deployment failed:", error);
  process.exitCode = 1;
});