const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const TransparentFund = await hre.ethers.getContractFactory("TransparentFund");
  const fund = await TransparentFund.deploy();
  await fund.waitForDeployment();

  const address = await fund.getAddress();
  console.log(`TransparentFund deployed to: ${address}`);

  // Create a config file for frontend
  const configContent = `// Auto-generated by deploy script
export const CONTRACT_ADDRESS = "${address}";
`;

  // Write to a temporary place or directly to frontend if possible
  const frontendConfigPath = path.join(__dirname, "../../frontend/src/utils/contractAddress.js");
  
  try {
    fs.mkdirSync(path.dirname(frontendConfigPath), { recursive: true });
    fs.writeFileSync(frontendConfigPath, configContent);
    console.log(`Contract address saved to frontend: ${frontendConfigPath}`);
  } catch (error) {
    console.warn("Could not save to frontend utils automatically. Save it manually: ", address);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
