const hre  = require("hardhat");
const fs   = require("fs");
const path = require("path");

async function main() {
  const network = hre.network.name;
  console.log(`\n🚀 Deploying USD-based contracts to network: ${network}`);

  const [deployer] = await hre.ethers.getSigners();
  console.log(`📦 Deploying from wallet:  ${deployer.address}`);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log(`💰 Wallet balance:          ${hre.ethers.formatEther(balance)} ETH\n`);

  // 1. Deploy MockUSDC
  console.log("Deploing MockUSDC...");
  const MockUSDC = await hre.ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log(`✅ MockUSDC deployed to: ${usdcAddress}`);

  // 2. Deploy TransparentFund
  console.log("Deploying TransparentFund...");
  const TransparentFund = await hre.ethers.getContractFactory("TransparentFund");
  const fund = await TransparentFund.deploy(usdcAddress);
  await fund.waitForDeployment();
  const fundAddress = await fund.getAddress();
  console.log(`✅ TransparentFund deployed to: ${fundAddress}`);

  // 3. Approve TransparentFund to spend deployer's USDC (Relayer capacity)
  console.log("Approving TransparentFund to spend deployer USDC...");
  const approveTx = await usdc.approve(fundAddress, hre.ethers.MaxUint256);
  await approveTx.wait(1);
  console.log("✅ Infinite USDC allowance granted to TransparentFund");

  // 4. Save addresses to frontend utils
  const configContent =
`// Auto-generated by blockchain/scripts/deploy.js — do NOT edit manually.
// Regenerate: npx hardhat run scripts/deploy.js --network <network>

export const CONTRACT_ADDRESS = "${fundAddress}";
export const USDC_ADDRESS     = "${usdcAddress}";
export const DEPLOYED_NETWORK = "${network}";
export const DEPLOYED_AT      = "${new Date().toISOString()}";
`;

  const destPath = path.join(__dirname, "../../frontend/src/utils/contractAddress.js");
  try {
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    fs.writeFileSync(destPath, configContent);
    console.log(`📁 Contract addresses saved to: ${destPath}`);
  } catch (err) {
    console.warn("⚠️ Could not auto-save to frontend contractAddress.js:", err.message);
  }

  // Also save to backend for relayer use
  const backendConfigContent =
`// Auto-generated by blockchain/scripts/deploy.js — do NOT edit manually.
module.exports = {
  CONTRACT_ADDRESS: "${fundAddress}",
  USDC_ADDRESS: "${usdcAddress}",
  DEPLOYED_NETWORK: "${network}"
};
`;
  const backendDestPath = path.join(__dirname, "../../backend/contractAddress.js");
  try {
    fs.writeFileSync(backendDestPath, backendConfigContent);
    console.log(`📁 Contract addresses saved to backend: ${backendDestPath}`);
  } catch (err) {
    console.warn("⚠️ Could not auto-save to backend contractAddress.js:", err.message);
  }

  // 5. Verification (skipped for local networks)
  if (network !== "localhost" && network !== "hardhat") {
    console.log("\n⏳ Waiting 15s before verification (block indexing delay)…");
    await new Promise(r => setTimeout(r, 15_000));
    try {
      await hre.run("verify:verify", {
        address: usdcAddress,
        constructorArguments: [],
      });
      console.log("✅ MockUSDC verified on Etherscan");
    } catch (e) {
      console.warn("⚠️ MockUSDC verification skipped:", e.message);
    }

    try {
      await hre.run("verify:verify", {
        address: fundAddress,
        constructorArguments: [usdcAddress],
      });
      console.log("✅ TransparentFund verified on Etherscan");
    } catch (e) {
      console.warn("⚠️ TransparentFund verification skipped:", e.message);
    }
  }

  console.log("\n🎉 Deployment and setup complete!\n");
}

main().catch(error => {
  console.error("❌ Deployment failed:", error);
  process.exitCode = 1;
});